
apiVersion: network.azure.com/v1api20220701
kind: PrivateEndpointsPrivateDnsZoneGroup
metadata:
  name: pe-aks-spoke-01-dnsgroup
  namespace: default
spec:
  owner:
    name: pe-aks-spoke-01

  privateDnsZoneConfigs:
    - name: aks-dns-config
      privateDnsZoneReference:
        armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/MC_rg-eus2-spoke-evergreen-01_aks-eus2-spoke-01_eastus2/providers/Microsoft.Network/privateDnsZones/<dns-zone-name>
