
apiVersion: network.azure.com/v1api20180901
kind: PrivateDnsZone
metadata:
  name: spoke-api-server-zone
  namespace: default
spec:
  location: global


  owner:
    armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/rg-eus2-hub-evergreen-01


  azureName: <dns-zone-name>
