apiVersion: network.azure.com/v1api20200601
kind: PrivateDnsZonesARecord
metadata:
  name: spoke-api-server-pe-override
  namespace: default
spec:
  azureName: <a-record-name>

  owner:
    armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/rg-eus2-hub-evergreen-01/providers/Microsoft.Network/privateDnsZones/<dns-zone-name>

  ttl: 300

  aRecords:
    - ipv4Address: <pe-nic-ip>
