
apiVersion: network.azure.com/v1api20220701
kind: PrivateEndpoint
metadata:
  name: pe-aks-spoke-01
  namespace: default
spec:
  location: eastus2


  owner:
    armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/rg-eus2-hub-evergreen-01

  subnet:
    reference:
      armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/rg-eus2-hub-evergreen-01/providers/Microsoft.Network/virtualNetworks/vnet-eus2-hub-evergreen-01/subnets/snet-pe

  privateLinkServiceConnections:
    - name: aksPrivateLink
      privateLinkServiceReference:
        armId: /subscriptions/f9ea6521-6599-4549-a5f1-5986548330f8/resourceGroups/rg-eus2-spoke-evergreen-01/providers/Microsoft.ContainerService/managedClusters/aks-eus2-spoke-01
      groupIds:
        - management
